server:
  port: 9000

spring:
  application:
    name: product-service

  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        delivery.timout.ms: 20000
        linger.ms: 0
        request.timeout: 10000
        enable.idempotence: true

